version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 174974734362.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t mapleliv-feign .
      - docker tag mapleliv-feign:latest 174974734362.dkr.ecr.us-east-2.amazonaws.com/mapleliv-feign:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 174974734362.dkr.ecr.us-east-2.amazonaws.com/mapleliv-feign:latest
      - printf '[{"name":"mapleliving-feign","imageUri":"174974734362.dkr.ecr.us-east-2.amazonaws.com/mapleliv-feign:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json